
package cn.qy.webservice.app02;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PhoneStore", targetNamespace = "http://app02.webService.qy.cn/", wsdlLocation = "http://127.0.0.1/webService/phoneStore?WSDL")
public class PhoneStore
    extends Service
{

    private final static URL PHONESTORE_WSDL_LOCATION;
    private final static WebServiceException PHONESTORE_EXCEPTION;
    private final static QName PHONESTORE_QNAME = new QName("http://app02.webService.qy.cn/", "PhoneStore");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1/webService/phoneStore?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PHONESTORE_WSDL_LOCATION = url;
        PHONESTORE_EXCEPTION = e;
    }

    public PhoneStore() {
        super(__getWsdlLocation(), PHONESTORE_QNAME);
    }

    public PhoneStore(WebServiceFeature... features) {
        super(__getWsdlLocation(), PHONESTORE_QNAME, features);
    }

    public PhoneStore(URL wsdlLocation) {
        super(wsdlLocation, PHONESTORE_QNAME);
    }

    public PhoneStore(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PHONESTORE_QNAME, features);
    }

    public PhoneStore(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PhoneStore(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PhoneService
     */
    @WebEndpoint(name = "PhoneServicePort")
    public PhoneService getPhoneServicePort() {
        return super.getPort(new QName("http://app02.webService.qy.cn/", "PhoneServicePort"), PhoneService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PhoneService
     */
    @WebEndpoint(name = "PhoneServicePort")
    public PhoneService getPhoneServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://app02.webService.qy.cn/", "PhoneServicePort"), PhoneService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PHONESTORE_EXCEPTION!= null) {
            throw PHONESTORE_EXCEPTION;
        }
        return PHONESTORE_WSDL_LOCATION;
    }

}
