
package cn.qy.webservice.app02;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PhoneService", targetNamespace = "http://app02.webService.qy.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PhoneService {


    /**
     * 
     * @param arg0
     * @return
     *     returns cn.qy.webservice.app02.Phone
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPhoneInformation", targetNamespace = "http://app02.webService.qy.cn/", className = "cn.qy.webservice.app02.GetPhoneInformation")
    @ResponseWrapper(localName = "getPhoneInformationResponse", targetNamespace = "http://app02.webService.qy.cn/", className = "cn.qy.webservice.app02.GetPhoneInformationResponse")
    @Action(input = "http://app02.webService.qy.cn/PhoneService/getPhoneInformationRequest", output = "http://app02.webService.qy.cn/PhoneService/getPhoneInformationResponse")
    public Phone getPhoneInformation(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
